/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Category" CASCADE;

CREATE TABLE "Category" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_category" TEXT NOT NULL);

