/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Department" CASCADE;

CREATE TABLE "Department" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_department" TEXT NOT NULL);

