// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef PC_ODB_HXX
#define PC_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "pc.h"

#include "category-odb.hxx"
#include "department-odb.hxx"
#include "po-odb.hxx"
#include "roles-odb.hxx"
#include "semi-odb.hxx"
#include "users-odb.hxx"
#include "version_po-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // PC
  //
  template <>
  struct class_traits< ::PC >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::PC >
  {
    public:
    typedef ::PC object_type;
    typedef ::PC* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // PC
  //
  template <typename A>
  struct pointer_query_columns< ::PC, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_pc_type_;

    static const name_pc_type_ name_pc;

    // department
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    department_type_;

    static const department_type_ department;
  };

  template <typename A>
  const typename pointer_query_columns< ::PC, id_pgsql, A >::id_type_
  pointer_query_columns< ::PC, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::PC, id_pgsql, A >::name_pc_type_
  pointer_query_columns< ::PC, id_pgsql, A >::
  name_pc (A::table_name, "\"name_pc\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::PC, id_pgsql, A >::department_type_
  pointer_query_columns< ::PC, id_pgsql, A >::
  department (A::table_name, "\"id_department\"", 0);

  template <>
  class access::object_traits_impl< ::PC, id_pgsql >:
    public access::object_traits< ::PC >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // name_pc
      //
      details::buffer name_pc_value;
      std::size_t name_pc_size;
      bool name_pc_null;

      // department
      //
      long long department_value;
      bool department_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // semis
    //
    struct semis_traits
    {
      static const char select_name[];
      static const char insert_name[];
      static const char delete_name[];

      static const unsigned int insert_types[];

      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::std::shared_ptr< ::Semi > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef pgsql::container_statements< semis_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        long long value_value;
        bool value_null;

        std::size_t version;
      };

      static void
      bind (pgsql::bind*,
            const pgsql::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    struct department_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::PC, id_common >:
    public access::object_traits_impl< ::PC, id_pgsql >
  {
  };

  // PC
  //
  template <>
  struct alias_traits<
    ::Department,
    id_pgsql,
    access::object_traits_impl< ::PC, id_pgsql >::department_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::PC, id_pgsql >
  {
    // department
    //
    typedef
    odb::alias_traits<
      ::Department,
      id_pgsql,
      access::object_traits_impl< ::PC, id_pgsql >::department_tag>
    department_alias_;
  };

  template <typename A>
  struct query_columns< ::PC, id_pgsql, A >:
    query_columns_base< ::PC, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // name_pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_pc_type_;

    static const name_pc_type_ name_pc;

    // department
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    department_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Department,
        id_pgsql,
        department_alias_ > >
    department_pointer_type_;

    struct department_type_: department_pointer_type_, department_column_type_
    {
      department_type_ (const char* t, const char* c, const char* conv)
        : department_column_type_ (t, c, conv)
      {
      }
    };

    static const department_type_ department;
  };

  template <typename A>
  const typename query_columns< ::PC, id_pgsql, A >::id_type_
  query_columns< ::PC, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::PC, id_pgsql, A >::name_pc_type_
  query_columns< ::PC, id_pgsql, A >::
  name_pc (A::table_name, "\"name_pc\"", 0);

  template <typename A>
  const typename query_columns< ::PC, id_pgsql, A >::department_type_
  query_columns< ::PC, id_pgsql, A >::
  department (A::table_name, "\"id_department\"", 0);
}

#include "pc-odb.ixx"

#include <odb/post.hxx>

#endif // PC_ODB_HXX
