/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "PC" CASCADE;

CREATE TABLE "PC" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_pc" TEXT NOT NULL,
  "id_department" BIGINT NOT NULL);

ALTER TABLE "PC"
  ADD CONSTRAINT "id_department_fk"
    FOREIGN KEY ("id_department")
    REFERENCES "Department" ("id")
    INITIALLY DEFERRED;

