/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "PO" CASCADE;

CREATE TABLE "PO" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_po" TEXT NOT NULL,
  "id_category" BIGINT NOT NULL);

ALTER TABLE "PO"
  ADD CONSTRAINT "id_category_fk"
    FOREIGN KEY ("id_category")
    REFERENCES "Category" ("id")
    INITIALLY DEFERRED;

