/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Roles" CASCADE;

CREATE TABLE "Roles" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_role" TEXT NOT NULL);

