// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef SEMI_ODB_HXX
#define SEMI_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "semi.h"

#include "category-odb.hxx"
#include "department-odb.hxx"
#include "pc-odb.hxx"
#include "po-odb.hxx"
#include "roles-odb.hxx"
#include "users-odb.hxx"
#include "version_po-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Semi
  //
  template <>
  struct class_traits< ::Semi >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Semi >
  {
    public:
    typedef ::Semi object_type;
    typedef ::Semi* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // Semi
  //
  template <typename A>
  struct pointer_query_columns< ::Semi, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    po_type_;

    static const po_type_ po;

    // pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    pc_type_;

    static const pc_type_ pc;
  };

  template <typename A>
  const typename pointer_query_columns< ::Semi, id_pgsql, A >::id_type_
  pointer_query_columns< ::Semi, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Semi, id_pgsql, A >::po_type_
  pointer_query_columns< ::Semi, id_pgsql, A >::
  po (A::table_name, "\"id_po\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::Semi, id_pgsql, A >::pc_type_
  pointer_query_columns< ::Semi, id_pgsql, A >::
  pc (A::table_name, "\"id_pc\"", 0);

  template <>
  class access::object_traits_impl< ::Semi, id_pgsql >:
    public access::object_traits< ::Semi >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // po
      //
      long long po_value;
      bool po_null;

      // pc
      //
      long long pc_value;
      bool pc_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct po_tag;
    struct pc_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Semi, id_common >:
    public access::object_traits_impl< ::Semi, id_pgsql >
  {
  };

  // Semi
  //
  template <>
  struct alias_traits<
    ::PO,
    id_pgsql,
    access::object_traits_impl< ::Semi, id_pgsql >::po_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::PC,
    id_pgsql,
    access::object_traits_impl< ::Semi, id_pgsql >::pc_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::Semi, id_pgsql >
  {
    // po
    //
    typedef
    odb::alias_traits<
      ::PO,
      id_pgsql,
      access::object_traits_impl< ::Semi, id_pgsql >::po_tag>
    po_alias_;

    // pc
    //
    typedef
    odb::alias_traits<
      ::PC,
      id_pgsql,
      access::object_traits_impl< ::Semi, id_pgsql >::pc_tag>
    pc_alias_;
  };

  template <typename A>
  struct query_columns< ::Semi, id_pgsql, A >:
    query_columns_base< ::Semi, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // po
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    po_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::PO,
        id_pgsql,
        po_alias_ > >
    po_pointer_type_;

    struct po_type_: po_pointer_type_, po_column_type_
    {
      po_type_ (const char* t, const char* c, const char* conv)
        : po_column_type_ (t, c, conv)
      {
      }
    };

    static const po_type_ po;

    // pc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    pc_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::PC,
        id_pgsql,
        pc_alias_ > >
    pc_pointer_type_;

    struct pc_type_: pc_pointer_type_, pc_column_type_
    {
      pc_type_ (const char* t, const char* c, const char* conv)
        : pc_column_type_ (t, c, conv)
      {
      }
    };

    static const pc_type_ pc;
  };

  template <typename A>
  const typename query_columns< ::Semi, id_pgsql, A >::id_type_
  query_columns< ::Semi, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::Semi, id_pgsql, A >::po_type_
  query_columns< ::Semi, id_pgsql, A >::
  po (A::table_name, "\"id_po\"", 0);

  template <typename A>
  const typename query_columns< ::Semi, id_pgsql, A >::pc_type_
  query_columns< ::Semi, id_pgsql, A >::
  pc (A::table_name, "\"id_pc\"", 0);
}

#include "semi-odb.ixx"

#include <odb/post.hxx>

#endif // SEMI_ODB_HXX
