/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Semi" CASCADE;

CREATE TABLE "Semi" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "id_po" BIGINT NOT NULL,
  "id_pc" BIGINT NOT NULL);

ALTER TABLE "Semi"
  ADD CONSTRAINT "id_po_fk"
    FOREIGN KEY ("id_po")
    REFERENCES "PO" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "id_pc_fk"
    FOREIGN KEY ("id_pc")
    REFERENCES "PC" ("id")
    INITIALLY DEFERRED;

