/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Users" CASCADE;

CREATE TABLE "Users" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name_user" TEXT NOT NULL,
  "id_department" BIGINT NOT NULL,
  "id_roles" BIGINT NOT NULL);

ALTER TABLE "Users"
  ADD CONSTRAINT "id_department_fk"
    FOREIGN KEY ("id_department")
    REFERENCES "Department" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "id_roles_fk"
    FOREIGN KEY ("id_roles")
    REFERENCES "Roles" ("id")
    INITIALLY DEFERRED;

