/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "VersionPO" CASCADE;

CREATE TABLE "VersionPO" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "version" TEXT NOT NULL,
  "date_version" TEXT NOT NULL,
  "id_po" BIGINT NOT NULL);

ALTER TABLE "VersionPO"
  ADD CONSTRAINT "id_po_fk"
    FOREIGN KEY ("id_po")
    REFERENCES "PO" ("id")
    INITIALLY DEFERRED;

